name: Sanity Check
on: [push]
jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          original: 'README.md'
          mirror: 'docs/README.md'
